### ISSUE TITLE
COUNT(*) bug

### ISSUE THREAD

**Issue by PiotrNowara** [sparqling/sparql-formatter#10]
Hi! when submitting a query with COUNT(*) got COUNT(undefined) in return.

`SELECT ?prop (COUNT(*) AS ?c) 
FROM <http://time.example/relations> WHERE {?e1 ?prop ?e2} 
GROUP BY ?prop`
![image](https://user-images.githubusercontent.com/25703717/213006377-9a26648e-6329-444b-a2c1-2302d3bf8225.png)

Cheers,
Piotr

**Comment by hchiba1** [comment]
Thanks! Fixed it.
